version: '3.8'
services:
  go-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=neo4j://neo4j:7687

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/testpass
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/conf
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
  neo4j_import:
  neo4j_plugins: